export const SPECIAL_NODE_COLORS = new Map<string, string>([
  ["_ghosts/GamesDB/Frostpunk", "#fcba03"],
  ["_ghosts/GamesDB/RimWorld", "#fcba03"],
  ["_ghosts/GamesDB/PlanetBase", "#fcba03"],
  ["_ghosts/GamesDB/Don't-Starve", "#fcba03"],
  ["_ghosts/GamesDB/The-Survivalists", "#fcba03"],
  ["_ghosts/GamesDB/GTA", "#fcba03"],
  ["_ghosts/GamesDB/Minecraft", "#fcba03"],
  ["_ghosts/GamesDB/Tropico", "#fcba03"],
  ["_ghosts/GamesDB/Factorio", "#fcba03"],
  ["_ghosts/GamesDB/Resident-Evil", "#fcba03"],
  ["_ghosts/GamesDB/Red-Dead-Redemption", "#fcba03"],
  ["_ghosts/GamesDB/Outlast", "#fcba03"],
  ["_ghosts/GamesDB/Valheim", "#fcba03"],
  ["_ghosts/GamesDB/Roblox", "#fcba03"],
  ["_ghosts/GamesDB/Raft", "#fcba03"],
])
